name: cron

on:
  push:
    branches:
      - main
  schedule:
<<<<<<< HEAD
    - cron: "0 22 * * *"
=======
    # Runs every sunday midnight
    - cron: '0 * * * *'
  workflow_dispatch:
>>>>>>> f6c1f90717a3182800a0998bf1c0ea49180ace0e

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🍽️ Get working copy
        uses: actions/checkout@master
        with:
<<<<<<< HEAD
          fetch-depth: 1                                                                 
      - name: 🐍 Set up Python 3.8                               
        uses: actions/setup-python@v2                               
        with:                                 
          python-version: '3.8'                                                   
      - name: 💿 Install feedparser & pytz                              
        run: pip install feedparser pytz
      - name: 🍳 Update README
        run: |
          cd ${GITHUB_WORKSPACE}/src/
          python blog_post_update.py
      - name: 🚀 Deploy
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "feat(auto generate): Updated content"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
=======
          max_post_count:  20
          feed_list: "https://medium.com/feed/@ealizadeh"
>>>>>>> f6c1f90717a3182800a0998bf1c0ea49180ace0e
